### ISSUE TITLE
Support Inertia 2.0

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/boring-stack#116]
### Description
In case you missed it, [Inertia 2.0 is on it's way](https://youtu.be/QYLHqAoo9Mk?si=vKr9LcjOUdkuK25i) and I am super excited of the features that it will be packed with.

To enjoy some of these features, inertia-sails - The official adapter for Inertia in Sails needs to be updated to support the server side features like merge props.

### Tasks
- [x] Implement deferred props
- [x] Implement except props
- [x] Implement optional props
- [x] Implement always props
- [x] Implement merge props
- [x] Simplify `inertia` custom response
- [x] Simplify `inertiaRedirect` custom response
- [x] Fix bug with `inertiaRedirect`
- [x] Implement `encryptHistory()`
- [x] Implement `clearHistory()`
- [x] Update `create-sails-generator` for generating `inertia` and `inertiaRedirect` custom responses
- [x] Update `mellow-react`
- [x] Update `mellow-vue`
- [x] Update `mellow-svelte`
- [x] Implement `handleBadRequest` to simplify `badRequest` custom response.
