### ISSUE TITLE
Update create-sails to support Ascent

### ISSUE THREAD

**Issue by DominusKelvin** [sailscastshq/boring-stack#120]
### Description
Make `create-sails` aware of the new Ascent templates
...

### Current behavior
Currently `create-sails` only assume to have Mellow as the template for TBJS. 
...

### Expected behavior

...

> Replace space in square bracket with `x` e.g `[x]`

- [ ] I have checked and this issue does not exist

## Todos
- [ ] Make `create-sails` take a flag to select templates. Maybe a `--a` for ascent or `--m` for mellow.
- [ ] Also modify the wizard to pop up a select for templates.
